version: "3.8"

services:
  employee-management-app:
    container_name: employee-management-container
    image: node:18
    working_dir: /app
    volumes:
      # Assuming Jenkins workspace is writable in this directory
      - /home/jenkins/workspace/project:/app
      - /app/node_modules  # Persist node_modules in container to avoid overwriting on every restart
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
