version: "3.8"

services:
  employee-management-app:
    container_name: employee-management-container
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # This helps prevent issues with host OS node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for live-reload on some systems
    depends_on:
      - db  # Add any other services if your app depends on them, like a database
    # If needed, uncomment the lines below to set up network or additional configs
    # networks:
    #   - my-network
